kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-filestore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-filestore
  storageClassName: ""