kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-filestore
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain #If set as "Delete" file share would be removed after pvc deletion
  csi:
    driver: filestore.csi.storage.gke.io
    readOnly: false
    volumeHandle: arbitrary-filestore-volume
    volumeAttributes:
      attrIP: e2e-test-peterhornyack-TODO
      attrVolume: Share
    nodePublishSecretRef:
      name: smb-secret
      namespace: default
